### ISSUE TITLE
Add steps to run locally

### ISSUE THREAD

**Issue by tanmayc07** [tanmayc07/Clemail#4]
The docs must contain proper steps for running the project locally.

**Comment by Rit-ctrl** [comment]
Created pull request #6 for this issue.

**Comment by tanmayc07** [comment]
Thank you for your contribution @Rit-ctrl 😀

**Comment by Rit-ctrl** [comment]
i missed a dot ig. It should be 
    `pip install -e .`

**Comment by tanmayc07** [comment]
Yeah I reverted the PR but I dont know how you are gonna push again?

**Comment by Rit-ctrl** [comment]
Should I make another pull request? Or is it possible for you to make the changes manually and close the issue?

**Comment by tanmayc07** [comment]
Make another PR. That'll be good

**Comment by tanmayc07** [comment]
Thank you @Rit-ctrl !
